config/routes.rb
Rails.application.routes.draw do
  root 'issues#index'
  resources :issues, only: [:index, :create, :new]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post '/update_state', to: 'issues#update_state'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/issue.rb
class Issue < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  # GET /issues
  # GET /issues.json
  def index
    @issues = Hash.new { |h,k| h[k] = [] }
    Issue.all.each do |issue|
      @issues[issue.state] << issue
    end
    @issues = @issues.sort.to_h
  end

  def update_state
    issue = Issue.find(params[:id])
    issue.update(state: params[:state])
    render json: {}
  end

  def create
    Issue.create(issue_params)
    redirect_to action: :index
  end

  private

  def issue_params
    params.permit(:description, :state)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<div class = 'creator-container'>
  <h1> Add new issue </h1>
  <%= form_tag issues_path, action: :post do %>
    <table class="form-table" border="0" cellpadding="0" cellspacing="5" class="table" width="100%">
      <tbody>
        <tr>
          <td>
            <%= label_tag 'issue_state', 'State' %>
          </td>
          <td>
            <%= text_field_tag 'state' %>
          </td>
        </tr>
        <tr>
          <td>
            <%= label_tag 'issue_description', 'Description' %>
          </td>
          <td>
            <%= text_field_tag 'description' %>
          </td>
        </tr>
      </tbody>
    </table>
    <%= submit_tag 'Create', class: 'submit-btn' %>
  <% end %>
</div>

app/views/issues/index.html.erb
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<div class = 'container'>
  <%= render 'form' %>
  <div class="tracker-container">
    <h1> Track Issues </h3>
    <ul class="list-container">
      <% @issues.each_with_index do |(state, issues), index| %>
        <li class="list col-md-3">
          <h3 class="issue-state"><%= state %></h3>
          <div class = 'partition'></div>
          <% issues.each do |issue| %>
            <div class = 'box'>
              <div class="issue-title" draggable="true">
                <div class = 'issue-id hidden'>
                  <%= issue.id %>
                </div>
                <%= issue.description %>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/issues/new.html.erb
<%= render 'form'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>